CREATE DATABASE SALES_SQL;
USE SALES_SQL;
SHOW TABLES;
SELECT * FROM SALES;
SELECT SALES.*,QUANTITYORDERED,PRODUCTCODE,CITY,CONTACTFIRSTNAME FROM SALES;
SELECT ORDERNUMBER,COUNT(*) FROM SALES GROUP BY ORDERNUMBER HAVING COUNT(*)>1;
SELECT COUNT(DISTINCT PRODUCTCODE) AS UNIQUEPRODUCTS FROM SALES;
SELECT ORDERNUMBER,SALES,(SALES*0.1) AS DISCOUNT_AMOUNT,(SALES-(SALES*0.1)) AS DISCOUNT_SALES FROM SALES;
SELECT ORDERNUMBER,(MSRP-PRICEEACH)*QUANTITYORDERED AS PROFIT FROM SALES;
SELECT COUNTRY,SUM(SALES) AS COUNTRY_SALES,(SUM(SALES)/(SELECT SUM(SALES) FROM SALES) * 100) AS PERCENTAGE_CONTRIBUTION 
       FROM SALES GROUP BY COUNTRY ORDER BY COUNTRY_SALES DESC;
SELECT YEAR_ID,QTR_ID,SUM(SALES) AS QuarterlySales FROM SALES GROUP BY YEAR_ID, QTR_ID;
SELECT ORDERNUMBER, CUSTOMERNAME, SALES FROM SALES WHERE SALES > 5000;
SELECT ORDERNUMBER, CUSTOMERNAME, PRODUCTLINE, COUNTRY FROM SALES WHERE COUNTRY = 'France' AND PRODUCTLINE = 'Motorcycles';
SELECT ORDERNUMBER, CUSTOMERNAME, SALES, QUANTITYORDERED FROM SALES WHERE SALES > 3000 AND QUANTITYORDERED < 40;
SELECT ORDERNUMBER, PRODUCTCODE, PRICEEACH, MSRP FROM SALES WHERE PRICEEACH = ANY (SELECT MSRP FROM SALES);
SELECT ORDERNUMBER, CUSTOMERNAME, SALES FROM SALES WHERE SALES > ALL (SELECT SALES FROM SALES WHERE COUNTRY = 'France');
SELECT CUSTOMERNAME, PRODUCTCODE, PRICEEACH,TERRITORY FROM SALES WHERE PRICEEACH > (SELECT AVG(PRICEEACH) FROM SALES);
SELECT ORDERDATE,PRODUCTCODE,SALES,CUSTOMERNAME,PHONE,ADDRESSLINE1,STATUS_ FROM SALES WHERE SALES IN 
       (SELECT MAX(SALES) FROM SALES WHERE SALES<
       (SELECT MAX(SALES) FROM SALES WHERE SALES<
       (SELECT MAX(SALES) FROM SALES)));
SELECT CUSTOMERNAME,ADDRESSLINE1,CITY,DEALSIZE,ORDERDATE,STATUS_,TERRITORY FROM SALES ORDER BY SALES DESC LIMIT 3;
SELECT o1.YEAR_ID,
       MAX(o1.SALES) AS HighestSale,
       MIN(o2.SALES) AS LowestSale
FROM SALES o1
JOIN SALES o2
  ON o1.YEAR_ID = o2.YEAR_ID
GROUP BY o1.YEAR_ID;
SELECT CUSTOMERNAME, PRODUCTLINE FROM sales WHERE PRODUCTLINE = 'Motorcycles'
UNION
SELECT CUSTOMERNAME, PRODUCTLINE FROM sales WHERE PRODUCTLINE = 'Classic Cars';






